### ISSUE TITLE
parametrize output and datafile names and path

### ISSUE THREAD

**Issue by smarru** [softmaterialslab/nanoconfinement-md#34]
Currently the outputfiles and datafiles are hard coded in the code. It will be nice to pass the path and file name as arguments and the program can use defaults when no such arguments are sent.

**Comment by jadhao** [comment]
we have followed the structure of executable in bin (or wherever it is on the HUB zero); we use ../data/xxx to hard code the output path still. tell us what should we do if you want to have dynamic path variables?

the issue is still open. we need to know the hierarchy of the directories. we could not see where the executable is on the nanohub. it is not in bin.

**Comment by jadhao** [comment]
@kadupitiya @smarru related to this issue, should we change the path to make dataclean to "../data/*.dat"? could be useful at the developer end.

**Comment by jadhao** [comment]
@kadupitiya @smarru i thikn this issue can be closed now as we have enough knowledge about what is going on.

**Comment by jadhao** [comment]
@smarru i prefer the person who opened the issue close it :)

**Comment by smarru** [comment]
yes @jadhao I think this can be closed as @kadupitiya is addressing it in the PR he is about to submit.

**Comment by kadupitiya** [comment]
Yes. It is almost done. :)
